apiVersion: v1
kind: Pod
metadata:
  name: asgn
  labels:
    app: asgnmt1
spec:
  containers:
  - name: asgn
    image: asgn:3.0
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
      hostPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: asgn-service
spec:
  selector:
    app: asgnmt1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


