version: '3'
services:
  db:
    image: postgres
    # container_name: "postgres-v12"
    ports:
        - "5432:5432/tcp"
    environment:
        - POSTGRES_USERNAME=root

        - POSTGRES_PASSWORD=root
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
  pgadmin:
        image: dpage/pgadmin4
        # container_name: pgadmin4
        ports:
            - "5050:80/tcp"
        environment:
            - PGADMIN_DEFAULT_EMAIL=root
            - PGADMIN_DEFAULT_PASSWORD=root

  app:
    # build: .
    image: 387333632d19cd9f6a40aef809f3b6407b36917ec428f193b819848532884553
    ports:
      - "8080:8080/tcp"
    depends_on:
      - db
    restart: on-failure
    networks:
      - my-network
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/assignment1

networks:
  my-network:

volumes:
  postgres-data: